MODULE km;

CONST

maxNameLength*       =       80
rows*                =       100
cols*                =       100
grayLevels*          =       255
prewitt*             =       1
peakSpace*           =       50
peaks*               =       30
kirsch*              =       2
sobel*               =       3
stackSize*           =       40000
stackFileLength*     =       500
forgetIt*            =      -50
stackFile*           =      "stack.tmp"


END km.
